services:  
  go-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
